version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports:
      - "15432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    networks:
      - postgres-network

  dbadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    networks:
      - postgres-network

volumes:
  postgresql-data:

networks:
  postgres-network:
    driver: bridge
